In [1]:
print("OK")

OK

mongodb+srv://arfin123:arfin123@cluster2.dopiv4y.mongodb.net/?appName=Cluster2

In [2]:
import pandas as pd

In [3]:
%pwd

'd:\\MLL-02\\End-to-End-Wine-Quality-Prediction\\notebooks'

In [4]:
df = pd.read_csv("winequality-red.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
df.shape

(1599, 12)

In [6]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')

In [7]:
data = df.to_dict(orient='records')
data

[{'fixed acidity': 7.4,
  'volatile acidity': 0.7,
  'citric acid': 0.0,
  'residual sugar': 1.9,
  'chlorides': 0.076,
  'free sulfur dioxide': 11.0,
  'total sulfur dioxide': 34.0,
  'density': 0.9978,
  'pH': 3.51,
  'sulphates': 0.56,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.88,
  'citric acid': 0.0,
  'residual sugar': 2.6,
  'chlorides': 0.098,
  'free sulfur dioxide': 25.0,
  'total sulfur dioxide': 67.0,
  'density': 0.9968,
  'pH': 3.2,
  'sulphates': 0.68,
  'alcohol': 9.8,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.76,
  'citric acid': 0.04,
  'residual sugar': 2.3,
  'chlorides': 0.092,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 54.0,
  'density': 0.997,
  'pH': 3.26,
  'sulphates': 0.65,
  'alcohol': 9.8,
  'quality': 5},
 {'fixed acidity': 11.2,
  'volatile acidity': 0.28,
  'citric acid': 0.56,
  'residual sugar': 1.9,
  'chlorides': 0.075,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 60.0,
  'density': 0.998,
  'pH': 3.16,
  'sulphates': 0.58,
  'alcohol': 9.8,
  'quality': 6},
 {'fixed acidity': 7.4,
  'volatile acidity': 0.7,
  'citric acid': 0.0,
  'residual sugar': 1.9,
  'chlorides': 0.076,
  'free sulfur dioxide': 11.0,
  'total sulfur dioxide': 34.0,
  'density': 0.9978,
  'pH': 3.51,
  'sulphates': 0.56,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.4,
  'volatile acidity': 0.66,
  'citric acid': 0.0,
  'residual sugar': 1.8,
  'chlorides': 0.075,
  'free sulfur dioxide': 13.0,
  'total sulfur dioxide': 40.0,
  'density': 0.9978,
  'pH': 3.51,
  'sulphates': 0.56,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.9,
  'volatile acidity': 0.6,
  'citric acid': 0.06,
  'residual sugar': 1.6,
  'chlorides': 0.069,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 59.0,
  'density': 0.9964,
  'pH': 3.3,
  'sulphates': 0.46,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.3,
  'volatile acidity': 0.65,
  'citric acid': 0.0,
  'residual sugar': 1.2,
  'chlorides': 0.065,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 21.0,
  'density': 0.9946,
  'pH': 3.39,
  'sulphates': 0.47,
  'alcohol': 10.0,
  'quality': 7},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.58,
  'citric acid': 0.02,
  'residual sugar': 2.0,
  'chlorides': 0.073,
  'free sulfur dioxide': 9.0,
  'total sulfur dioxide': 18.0,
  'density': 0.9968,
  'pH': 3.36,
  'sulphates': 0.57,
  'alcohol': 9.5,
  'quality': 7},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.5,
  'citric acid': 0.36,
  'residual sugar': 6.1,
  'chlorides': 0.071,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 102.0,
  'density': 0.9978,
  'pH': 3.35,
  'sulphates': 0.8,
  'alcohol': 10.5,
  'quality': 5},
 {'fixed acidity': 6.7,
  'volatile acidity': 0.58,
  'citric acid': 0.08,
  'residual sugar': 1.8,
  'chlorides': 0.0969999999999999,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 65.0,
  'density': 0.9959,
  'pH': 3.28,
  'sulphates': 0.54,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.5,
  'citric acid': 0.36,
  'residual sugar': 6.1,
  'chlorides': 0.071,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 102.0,
  'density': 0.9978,
  'pH': 3.35,
  'sulphates': 0.8,
  'alcohol': 10.5,
  'quality': 5},
 {'fixed acidity': 5.6,
  'volatile acidity': 0.615,
  'citric acid': 0.0,
  'residual sugar': 1.6,
  'chlorides': 0.089,
  'free sulfur dioxide': 16.0,
  'total sulfur dioxide': 59.0,
  'density': 0.9943,
  'pH': 3.58,
  'sulphates': 0.52,
  'alcohol': 9.9,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.61,
  'citric acid': 0.29,
  'residual sugar': 1.6,
  'chlorides': 0.114,
  'free sulfur dioxide': 9.0,
  'total sulfur dioxide': 29.0,
  'density': 0.9974,
  'pH': 3.26,
  'sulphates': 1.56,
  'alcohol': 9.1,
  'quality': 5},
 {'fixed acidity': 8.9,
  'volatile acidity': 0.62,
  'citric acid': 0.18,
  'residual sugar': 3.8,
  'chlorides': 0.176,
  'free sulfur dioxide': 52.0,
  'total sulfur dioxide': 145.0,
  'density': 0.9986,
  'pH': 3.16,
  'sulphates': 0.88,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 8.9,
  'volatile acidity': 0.62,
  'citric acid': 0.19,
  'residual sugar': 3.9,
  'chlorides': 0.17,
  'free sulfur dioxide': 51.0,
  'total sulfur dioxide': 148.0,
  'density': 0.9986,
  'pH': 3.17,
  'sulphates': 0.93,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 8.5,
  'volatile acidity': 0.28,
  'citric acid': 0.56,
  'residual sugar': 1.8,
  'chlorides': 0.092,
  'free sulfur dioxide': 35.0,
  'total sulfur dioxide': 103.0,
  'density': 0.9969,
  'pH': 3.3,
  'sulphates': 0.75,
  'alcohol': 10.5,
  'quality': 7},
 {'fixed acidity': 8.1,
  'volatile acidity': 0.56,
  'citric acid': 0.28,
  'residual sugar': 1.7,
  'chlorides': 0.368,
  'free sulfur dioxide': 16.0,
  'total sulfur dioxide': 56.0,
  'density': 0.9968,
  'pH': 3.11,
  'sulphates': 1.28,
  'alcohol': 9.3,
  'quality': 5},
 {'fixed acidity': 7.4,
  'volatile acidity': 0.59,
  'citric acid': 0.08,
  'residual sugar': 4.4,
  'chlorides': 0.086,
  'free sulfur dioxide': 6.0,
  'total sulfur dioxide': 29.0,
  'density': 0.9974,
  'pH': 3.38,
  'sulphates': 0.5,
  'alcohol': 9.0,
  'quality': 4},
 {'fixed acidity': 7.9,
  'volatile acidity': 0.32,
  'citric acid': 0.51,
  'residual sugar': 1.8,
  'chlorides': 0.341,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 56.0,
  'density': 0.9969,
  'pH': 3.04,
  'sulphates': 1.08,
  'alcohol': 9.2,
  'quality': 6},
 {'fixed acidity': 8.9,
  'volatile acidity': 0.22,
  'citric acid': 0.48,
  'residual sugar': 1.8,
  'chlorides': 0.077,
  'free sulfur dioxide': 29.0,
  'total sulfur dioxide': 60.0,
  'density': 0.9968,
  'pH': 3.39,
  'sulphates': 0.53,
  'alcohol': 9.4,
  'quality': 6},
 {'fixed acidity': 7.6,
  'volatile acidity': 0.39,
  'citric acid': 0.31,
  'residual sugar': 2.3,
  'chlorides': 0.0819999999999999,
  'free sulfur dioxide': 23.0,
  'total sulfur dioxide': 71.0,
  'density': 0.9982,
  'pH': 3.52,
  'sulphates': 0.65,
  'alcohol': 9.7,
  'quality': 5},
 {'fixed acidity': 7.9,
  'volatile acidity': 0.43,
  'citric acid': 0.21,
  'residual sugar': 1.6,
  'chlorides': 0.106,
  'free sulfur dioxide': 10.0,
  'total sulfur dioxide': 37.0,
  'density': 0.9966,
  'pH': 3.17,
  'sulphates': 0.91,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 8.5,
  'volatile acidity': 0.49,
  'citric acid': 0.11,
  'residual sugar': 2.3,
  'chlorides': 0.084,
  'free sulfur dioxide': 9.0,
  'total sulfur dioxide': 67.0,
  'density': 0.9968,
  'pH': 3.17,
  'sulphates': 0.53,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 6.9,
  'volatile acidity': 0.4,
  'citric acid': 0.14,
  'residual sugar': 2.4,
  'chlorides': 0.085,
  'free sulfur dioxide': 21.0,
  'total sulfur dioxide': 40.0,
  'density': 0.9968,
  'pH': 3.43,
  'sulphates': 0.63,
  'alcohol': 9.7,
  'quality': 6},
 {'fixed acidity': 6.3,
  'volatile acidity': 0.39,
  'citric acid': 0.16,
  'residual sugar': 1.4,
  'chlorides': 0.08,
  'free sulfur dioxide': 11.0,
  'total sulfur dioxide': 23.0,
  'density': 0.9955,
  'pH': 3.34,
  'sulphates': 0.56,
  'alcohol': 9.3,
  'quality': 5},
 {'fixed acidity': 7.6,
  'volatile acidity': 0.41,
  'citric acid': 0.24,
  'residual sugar': 1.8,
  'chlorides': 0.08,
  'free sulfur dioxide': 4.0,
  'total sulfur dioxide': 11.0,
  'density': 0.9962,
  'pH': 3.28,
  'sulphates': 0.59,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 7.9,
  'volatile acidity': 0.43,
  'citric acid': 0.21,
  'residual sugar': 1.6,
  'chlorides': 0.106,
  'free sulfur dioxide': 10.0,
  'total sulfur dioxide': 37.0,
  'density': 0.9966,
  'pH': 3.17,
  'sulphates': 0.91,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 7.1,
  'volatile acidity': 0.71,
  'citric acid': 0.0,
  'residual sugar': 1.9,
  'chlorides': 0.08,
  'free sulfur dioxide': 14.0,
  'total sulfur dioxide': 35.0,
  'density': 0.9972,
  'pH': 3.47,
  'sulphates': 0.55,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.645,
  'citric acid': 0.0,
  'residual sugar': 2.0,
  'chlorides': 0.0819999999999999,
  'free sulfur dioxide': 8.0,
  'total sulfur dioxide': 16.0,
  'density': 0.9964,
  'pH': 3.38,
  'sulphates': 0.59,
  'alcohol': 9.8,
  'quality': 6},
 {'fixed acidity': 6.7,
  'volatile acidity': 0.675,
  'citric acid': 0.07,
  'residual sugar': 2.4,
  'chlorides': 0.089,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 82.0,
  'density': 0.9958,
  'pH': 3.35,
  'sulphates': 0.54,
  'alcohol': 10.1,
  'quality': 5},
 {'fixed acidity': 6.9,
  'volatile acidity': 0.685,
  'citric acid': 0.0,
  'residual sugar': 2.5,
  'chlorides': 0.105,
  'free sulfur dioxide': 22.0,
  'total sulfur dioxide': 37.0,
  'density': 0.9966,
  'pH': 3.46,
  'sulphates': 0.57,
  'alcohol': 10.6,
  'quality': 6},
 {'fixed acidity': 8.3,
  'volatile acidity': 0.655,
  'citric acid': 0.12,
  'residual sugar': 2.3,
  'chlorides': 0.083,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 113.0,
  'density': 0.9966,
  'pH': 3.17,
  'sulphates': 0.66,
  'alcohol': 9.8,
  'quality': 5},
 {'fixed acidity': 6.9,
  'volatile acidity': 0.605,
  'citric acid': 0.12,
  'residual sugar': 10.7,
  'chlorides': 0.073,
  'free sulfur dioxide': 40.0,
  'total sulfur dioxide': 83.0,
  'density': 0.9993,
  'pH': 3.45,
  'sulphates': 0.52,
  'alcohol': 9.4,
  'quality': 6},
 {'fixed acidity': 5.2,
  'volatile acidity': 0.32,
  'citric acid': 0.25,
  'residual sugar': 1.8,
  'chlorides': 0.103,
  'free sulfur dioxide': 13.0,
  'total sulfur dioxide': 50.0,
  'density': 0.9957,
  'pH': 3.38,
  'sulphates': 0.55,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.645,
  'citric acid': 0.0,
  'residual sugar': 5.5,
  'chlorides': 0.086,
  'free sulfur dioxide': 5.0,
  'total sulfur dioxide': 18.0,
  'density': 0.9986,
  'pH': 3.4,
  'sulphates': 0.55,
  'alcohol': 9.6,
  'quality': 6},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.6,
  'citric acid': 0.14,
  'residual sugar': 2.4,
  'chlorides': 0.086,
  'free sulfur dioxide': 3.0,
  'total sulfur dioxide': 15.0,
  'density': 0.9975,
  'pH': 3.42,
  'sulphates': 0.6,
  'alcohol': 10.8,
  'quality': 6},
 {'fixed acidity': 8.1,
  'volatile acidity': 0.38,
  'citric acid': 0.28,
  'residual sugar': 2.1,
  'chlorides': 0.066,
  'free sulfur dioxide': 13.0,
  'total sulfur dioxide': 30.0,
  'density': 0.9968,
  'pH': 3.23,
  'sulphates': 0.73,
  'alcohol': 9.7,
  'quality': 7},
 {'fixed acidity': 5.7,
  'volatile acidity': 1.13,
  'citric acid': 0.09,
  'residual sugar': 1.5,
  'chlorides': 0.172,
  'free sulfur dioxide': 7.0,
  'total sulfur dioxide': 19.0,
  'density': 0.994,
  'pH': 3.5,
  'sulphates': 0.48,
  'alcohol': 9.8,
  'quality': 4},
 {'fixed acidity': 7.3,
  'volatile acidity': 0.45,
  'citric acid': 0.36,
  'residual sugar': 5.9,
  'chlorides': 0.074,
  'free sulfur dioxide': 12.0,
  'total sulfur dioxide': 87.0,
  'density': 0.9978,
  'pH': 3.33,
  'sulphates': 0.83,
  'alcohol': 10.5,
  'quality': 5},
 {'fixed acidity': 7.3,
  'volatile acidity': 0.45,
  'citric acid': 0.36,
  'residual sugar': 5.9,
  'chlorides': 0.074,
  'free sulfur dioxide': 12.0,
  'total sulfur dioxide': 87.0,
  'density': 0.9978,
  'pH': 3.33,
  'sulphates': 0.83,
  'alcohol': 10.5,
  'quality': 5},
 {'fixed acidity': 8.8,
  'volatile acidity': 0.61,
  'citric acid': 0.3,
  'residual sugar': 2.8,
  'chlorides': 0.088,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 46.0,
  'density': 0.9976,
  'pH': 3.26,
  'sulphates': 0.51,
  'alcohol': 9.3,
  'quality': 4},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.49,
  'citric acid': 0.2,
  'residual sugar': 2.6,
  'chlorides': 0.332,
  'free sulfur dioxide': 8.0,
  'total sulfur dioxide': 14.0,
  'density': 0.9968,
  'pH': 3.21,
  'sulphates': 0.9,
  'alcohol': 10.5,
  'quality': 6},
 {'fixed acidity': 8.1,
  'volatile acidity': 0.66,
  'citric acid': 0.22,
  'residual sugar': 2.2,
  'chlorides': 0.069,
  'free sulfur dioxide': 9.0,
  'total sulfur dioxide': 23.0,
  'density': 0.9968,
  'pH': 3.3,
  'sulphates': 1.2,
  'alcohol': 10.3,
  'quality': 5},
 {'fixed acidity': 6.8,
  'volatile acidity': 0.67,
  'citric acid': 0.02,
  'residual sugar': 1.8,
  'chlorides': 0.05,
  'free sulfur dioxide': 5.0,
  'total sulfur dioxide': 11.0,
  'density': 0.9962,
  'pH': 3.48,
  'sulphates': 0.52,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 4.6,
  'volatile acidity': 0.52,
  'citric acid': 0.15,
  'residual sugar': 2.1,
  'chlorides': 0.054,
  'free sulfur dioxide': 8.0,
  'total sulfur dioxide': 65.0,
  'density': 0.9934,
  'pH': 3.9,
  'sulphates': 0.56,
  'alcohol': 13.1,
  'quality': 4},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.935,
  'citric acid': 0.43,
  'residual sugar': 2.2,
  'chlorides': 0.114,
  'free sulfur dioxide': 22.0,
  'total sulfur dioxide': 114.0,
  'density': 0.997,
  'pH': 3.25,
  'sulphates': 0.73,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 8.7,
  'volatile acidity': 0.29,
  'citric acid': 0.52,
  'residual sugar': 1.6,
  'chlorides': 0.113,
  'free sulfur dioxide': 12.0,
  'total sulfur dioxide': 37.0,
  'density': 0.9969,
  'pH': 3.25,
  'sulphates': 0.58,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 6.4,
  'volatile acidity': 0.4,
  'citric acid': 0.23,
  'residual sugar': 1.6,
  'chlorides': 0.066,
  'free sulfur dioxide': 5.0,
  'total sulfur dioxide': 12.0,
  'density': 0.9958,
  'pH': 3.34,
  'sulphates': 0.56,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 5.6,
  'volatile acidity': 0.31,
  'citric acid': 0.37,
  'residual sugar': 1.4,
  'chlorides': 0.074,
  'free sulfur dioxide': 12.0,
  'total sulfur dioxide': 96.0,
  'density': 0.9954,
  'pH': 3.32,
  'sulphates': 0.58,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 8.8,
  'volatile acidity': 0.66,
  'citric acid': 0.26,
  'residual sugar': 1.7,
  'chlorides': 0.074,
  'free sulfur dioxide': 4.0,
  'total sulfur dioxide': 23.0,
  'density': 0.9971,
  'pH': 3.15,
  'sulphates': 0.74,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 6.6,
  'volatile acidity': 0.52,
  'citric acid': 0.04,
  'residual sugar': 2.2,
  'chlorides': 0.069,
  'free sulfur dioxide': 8.0,
  'total sulfur dioxide': 15.0,
  'density': 0.9956,
  'pH': 3.4,
  'sulphates': 0.63,
  'alcohol': 9.4,
  'quality': 6},
 {'fixed acidity': 6.6,
  'volatile acidity': 0.5,
  'citric acid': 0.04,
  'residual sugar': 2.1,
  'chlorides': 0.068,
  'free sulfur dioxide': 6.0,
  'total sulfur dioxide': 14.0,
  'density': 0.9955,
  'pH': 3.39,
  'sulphates': 0.64,
  'alcohol': 9.4,
  'quality': 6},
 {'fixed acidity': 8.6,
  'volatile acidity': 0.38,
  'citric acid': 0.36,
  'residual sugar': 3.0,
  'chlorides': 0.081,
  'free sulfur dioxide': 30.0,
  'total sulfur dioxide': 119.0,
  'density': 0.997,
  'pH': 3.2,
  'sulphates': 0.56,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.6,
  'volatile acidity': 0.51,
  'citric acid': 0.15,
  'residual sugar': 2.8,
  'chlorides': 0.11,
  'free sulfur dioxide': 33.0,
  'total sulfur dioxide': 73.0,
  'density': 0.9955,
  'pH': 3.17,
  'sulphates': 0.63,
  'alcohol': 10.2,
  'quality': 6},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.62,
  'citric acid': 0.04,
  'residual sugar': 3.8,
  'chlorides': 0.084,
  'free sulfur dioxide': 25.0,
  'total sulfur dioxide': 45.0,
  'density': 0.9978,
  'pH': 3.34,
  'sulphates': 0.53,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 10.2,
  'volatile acidity': 0.42,
  'citric acid': 0.57,
  'residual sugar': 3.4,
  'chlorides': 0.07,
  'free sulfur dioxide': 4.0,
  'total sulfur dioxide': 10.0,
  'density': 0.9971,
  'pH': 3.04,
  'sulphates': 0.63,
  'alcohol': 9.6,
  'quality': 5},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.63,
  'citric acid': 0.12,
  'residual sugar': 5.1,
  'chlorides': 0.111,
  'free sulfur dioxide': 50.0,
  'total sulfur dioxide': 110.0,
  'density': 0.9983,
  'pH': 3.26,
  'sulphates': 0.77,
  'alcohol': 9.4,
  'quality': 5},
 {'fixed acidity': 7.8,
  'volatile acidity': 0.59,
  'citric acid': 0.18,
  'residual sugar': 2.3,
  'chlorides': 0.076,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 54.0,
  'density': 0.9975,
  'pH': 3.43,
  'sulphates': 0.59,
  'alcohol': 10.0,
  'quality': 5},
 {'fixed acidity': 7.3,
  'volatile acidity': 0.39,
  'citric acid': 0.31,
  'residual sugar': 2.4,
  'chlorides': 0.074,
  'free sulfur dioxide': 9.0,
  'total sulfur dioxide': 46.0,
  'density': 0.9962,
  'pH': 3.41,
  'sulphates': 0.54,
  'alcohol': 9.4,
  'quality': 6},
 {'fixed acidity': 8.8,
  'volatile acidity': 0.4,
  'citric acid': 0.4,
  'residual sugar': 2.2,
  'chlorides': 0.079,
  'free sulfur dioxide': 19.0,
  'total sulfur dioxide': 52.0,
  'density': 0.998,
  'pH': 3.44,
  'sulphates': 0.64,
  'alcohol': 9.2,
  'quality': 5},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.69,
  'citric acid': 0.49,
  'residual sugar': 1.8,
  'chlorides': 0.115,
  'free sulfur dioxide': 20.0,
  'total sulfur dioxide': 112.0,
  'density': 0.9968,
  'pH': 3.21,
  'sulphates': 0.71,
  'alcohol': 9.3,
  'quality': 5},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.52,
  'citric acid': 0.16,
  'residual sugar': 1.9,
  'chlorides': 0.085,
  'free sulfur dioxide': 12.0,
  'total sulfur dioxide': 35.0,
  'density': 0.9968,
  'pH': 3.38,
  'sulphates': 0.62,
  'alcohol': 9.5,
  'quality': 7},
 {'fixed acidity': 7.0,
  'volatile acidity': 0.735,
  'citric acid': 0.05,
  'residual sugar': 2.0,
  'chlorides': 0.081,
  'free sulfur dioxide': 13.0,
  'total sulfur dioxide': 54.0,
  'density': 0.9966,
  'pH': 3.39,
  'sulphates': 0.57,
  'alcohol': 9.8,
  'quality': 5},
 {'fixed acidity': 7.2,
  'volatile acidity': 0.725,
  'citric acid': 0.05,
  'residual sugar': 4.65,
  'chlorides': 0.086,
  'free sulfur dioxide': 4.0,
  'total sulfur dioxide': 11.0,
  'density': 0.9962,
  'pH': 3.41,
  'sulphates': 0.39,
  'alcohol': 10.9,
  'quality': 5},
 {'fixed acidity': 7.2,
  'volatile acidity': 0.725,
  'citric acid': 0.05,
  'residual sugar': 4.65,
  'chlorides': 0.086,
  'free sulfur dioxide': 4.0,
  'total sulfur dioxide': 11.0,
  'density': 0.9962,
  'pH': 3.41,
  'sulphates': 0.39,
  'alcohol': 10.9,
  'quality': 5},
 {'fixed acidity': 7.5,
  'volatile acidity': 0.52,
  'citric acid': 0.11,
  'residual sugar': 1.5,
  'chlorides': 0.079,
  'free sulfur dioxide': 11.0,
  'total sulfur dioxide': 39.0,
  'density': 0.9968,
  'pH': 3.42,
  'sulphates': 0.58,
  'alcohol': 9.6,
  'quality': 5},
 {'fixed acidity': 6.6,
  'volatile acidity': 0.705,
  'citric acid': 0.07,
  'residual sugar': 1.6,
  'chlorides': 0.076,
  'free sulfur dioxide': 6.0,
  'total sulfur dioxide': 15.0,
  'density': 0.9962,
  'pH': 3.44,
  'sulphates': 0.58,
  'alcohol': 10.7,
  'quality': 5},
 {'fixed acidity': 9.3,
  'volatile acidity': 0.32,
  'citric acid': 0.57,
  'residual sugar': 2.0,
  'chlorides': 0.074,
  'free sulfur dioxide': 27.0,
  'total sulfur dioxide': 65.0,
  'density': 0.9969,
  'pH': 3.28,
  'sulphates': 0.79,
  'alcohol': 10.7,
  'quality': 5},
 {'fixed acidity': 8.0,
  'volatile acidity': 0.705,
  'citric acid': 0.05,
  'residual sugar': 1.9,
  'chlorides': 0.074,
  'free sulfur dioxide': 8.0,
  'total sulfur dioxide': 19.0,
  'density': 0.9962,
  'pH': 3.34,
  'sulphates': 0.95,
  'alcohol': 10.5,
  'quality': 6},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.63,
  'citric acid': 0.08,
  'residual sugar': 1.9,
  'chlorides': 0.076,
  'free sulfur dioxide': 15.0,
  'total sulfur dioxide': 27.0,
  'density': 0.9967,
  'pH': 3.32,
  'sulphates': 0.54,
  'alcohol': 9.5,
  'quality': 6},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.67,
  'citric acid': 0.23,
  'residual sugar': 2.1,
  'chlorides': 0.088,
  'free sulfur dioxide': 17.0,
  'total sulfur dioxide': 96.0,
  'density': 0.9962,
  'pH': 3.32,
  'sulphates': 0.48,
  'alcohol': 9.5,
  'quality': 5},
 {'fixed acidity': 7.7,
  'volatile acidity': 0.69,
  'citric acid': 0.22,
  'residual sugar': 1.9,

In [8]:
DB_NAME = "Wine_Quality_Prediction"
COLLECTION_NAME = "wine_data"
CONNECTION_URL = "mongodb+srv://arfin123:arfin123@cluster2.dopiv4y.mongodb.net/?appName=Cluster2"

In [11]:
import pandas as pd
from pymongo import MongoClient

# === STEP 1: Load your dataset ===
file_path = "winequality-red.csv"
df = pd.read_csv(file_path)

# Convert DataFrame to dictionary (records)
data = df.to_dict(orient="records")

# === STEP 2: Connect to MongoDB Atlas ===
# Replace with your actual connection string
MONGO_URI = "mongodb+srv://arfin123:arfin123@cluster2.dopiv4y.mongodb.net/?appName=Cluster2"

client = MongoClient(MONGO_URI)

# === STEP 3: Create / access database and collection ===
db = client["Wine_Quality_Prediction"]          # database name
collection = db["wine_data"]   # collection name

# === STEP 4: Insert data into MongoDB ===
collection.insert_many(data)

print("✅ Data successfully uploaded to MongoDB Atlas!")

✅ Data successfully uploaded to MongoDB Atlas!

In [12]:
print(client.list_database_names())

['Wine_Quality_Prediction', 'admin', 'local']

In [13]:
print(collection.count_documents({}))
print(collection.find_one())

1599
{'_id': ObjectId('6a1073330a6ca7c75455d4e9'), 'fixed acidity': 7.4, 'volatile acidity': 0.7, 'citric acid': 0.0, 'residual sugar': 1.9, 'chlorides': 0.076, 'free sulfur dioxide': 11.0, 'total sulfur dioxide': 34.0, 'density': 0.9978, 'pH': 3.51, 'sulphates': 0.56, 'alcohol': 9.4, 'quality': 5}

# Get Data

In [14]:
records = collection.find()

for i, record in enumerate(records):
    print(f"{i} : {record}")

# close AFTER loop (if needed)
# client.close()

0 : {'_id': ObjectId('6a1073330a6ca7c75455d4e9'), 'fixed acidity': 7.4, 'volatile acidity': 0.7, 'citric acid': 0.0, 'residual sugar': 1.9, 'chlorides': 0.076, 'free sulfur dioxide': 11.0, 'total sulfur dioxide': 34.0, 'density': 0.9978, 'pH': 3.51, 'sulphates': 0.56, 'alcohol': 9.4, 'quality': 5}
1 : {'_id': ObjectId('6a1073330a6ca7c75455d4ea'), 'fixed acidity': 7.8, 'volatile acidity': 0.88, 'citric acid': 0.0, 'residual sugar': 2.6, 'chlorides': 0.098, 'free sulfur dioxide': 25.0, 'total sulfur dioxide': 67.0, 'density': 0.9968, 'pH': 3.2, 'sulphates': 0.68, 'alcohol': 9.8, 'quality': 5}
2 : {'_id': ObjectId('6a1073330a6ca7c75455d4eb'), 'fixed acidity': 7.8, 'volatile acidity': 0.76, 'citric acid': 0.04, 'residual sugar': 2.3, 'chlorides': 0.092, 'free sulfur dioxide': 15.0, 'total sulfur dioxide': 54.0, 'density': 0.997, 'pH': 3.26, 'sulphates': 0.65, 'alcohol': 9.8, 'quality': 5}
3 : {'_id': ObjectId('6a1073330a6ca7c75455d4ec'), 'fixed acidity': 11.2, 'volatile acidity': 0.28, 'citric acid': 0.56, 'residual sugar': 1.9, 'chlorides': 0.075, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 60.0, 'density': 0.998, 'pH': 3.16, 'sulphates': 0.58, 'alcohol': 9.8, 'quality': 6}
4 : {'_id': ObjectId('6a1073330a6ca7c75455d4ed'), 'fixed acidity': 7.4, 'volatile acidity': 0.7, 'citric acid': 0.0, 'residual sugar': 1.9, 'chlorides': 0.076, 'free sulfur dioxide': 11.0, 'total sulfur dioxide': 34.0, 'density': 0.9978, 'pH': 3.51, 'sulphates': 0.56, 'alcohol': 9.4, 'quality': 5}
5 : {'_id': ObjectId('6a1073330a6ca7c75455d4ee'), 'fixed acidity': 7.4, 'volatile acidity': 0.66, 'citric acid': 0.0, 'residual sugar': 1.8, 'chlorides': 0.075, 'free sulfur dioxide': 13.0, 'total sulfur dioxide': 40.0, 'density': 0.9978, 'pH': 3.51, 'sulphates': 0.56, 'alcohol': 9.4, 'quality': 5}
6 : {'_id': ObjectId('6a1073330a6ca7c75455d4ef'), 'fixed acidity': 7.9, 'volatile acidity': 0.6, 'citric acid': 0.06, 'residual sugar': 1.6, 'chlorides': 0.069, 'free sulfur dioxide': 15.0, 'total sulfur dioxide': 59.0, 'density': 0.9964, 'pH': 3.3, 'sulphates': 0.46, 'alcohol': 9.4, 'quality': 5}
7 : {'_id': ObjectId('6a1073330a6ca7c75455d4f0'), 'fixed acidity': 7.3, 'volatile acidity': 0.65, 'citric acid': 0.0, 'residual sugar': 1.2, 'chlorides': 0.065, 'free sulfur dioxide': 15.0, 'total sulfur dioxide': 21.0, 'density': 0.9946, 'pH': 3.39, 'sulphates': 0.47, 'alcohol': 10.0, 'quality': 7}
8 : {'_id': ObjectId('6a1073330a6ca7c75455d4f1'), 'fixed acidity': 7.8, 'volatile acidity': 0.58, 'citric acid': 0.02, 'residual sugar': 2.0, 'chlorides': 0.073, 'free sulfur dioxide': 9.0, 'total sulfur dioxide': 18.0, 'density': 0.9968, 'pH': 3.36, 'sulphates': 0.57, 'alcohol': 9.5, 'quality': 7}
9 : {'_id': ObjectId('6a1073330a6ca7c75455d4f2'), 'fixed acidity': 7.5, 'volatile acidity': 0.5, 'citric acid': 0.36, 'residual sugar': 6.1, 'chlorides': 0.071, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 102.0, 'density': 0.9978, 'pH': 3.35, 'sulphates': 0.8, 'alcohol': 10.5, 'quality': 5}
10 : {'_id': ObjectId('6a1073330a6ca7c75455d4f3'), 'fixed acidity': 6.7, 'volatile acidity': 0.58, 'citric acid': 0.08, 'residual sugar': 1.8, 'chlorides': 0.0969999999999999, 'free sulfur dioxide': 15.0, 'total sulfur dioxide': 65.0, 'density': 0.9959, 'pH': 3.28, 'sulphates': 0.54, 'alcohol': 9.2, 'quality': 5}
11 : {'_id': ObjectId('6a1073330a6ca7c75455d4f4'), 'fixed acidity': 7.5, 'volatile acidity': 0.5, 'citric acid': 0.36, 'residual sugar': 6.1, 'chlorides': 0.071, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 102.0, 'density': 0.9978, 'pH': 3.35, 'sulphates': 0.8, 'alcohol': 10.5, 'quality': 5}
12 : {'_id': ObjectId('6a1073330a6ca7c75455d4f5'), 'fixed acidity': 5.6, 'volatile acidity': 0.615, 'citric acid': 0.0, 'residual sugar': 1.6, 'chlorides': 0.089, 'free sulfur dioxide': 16.0, 'total sulfur dioxide': 59.0, 'density': 0.9943, 'pH': 3.58, 'sulphates': 0.52, 'alcohol': 9.9, 'quality': 5}
13 : {'_id': ObjectId('6a1073330a6ca7c75455d4f6'), 'fixed acidity': 7.8, 'volatile acidity': 0.61, 'citric acid': 0.29, 'residual sugar': 1.6, 'chlorides': 0.114, 'free sulfur dioxide': 9.0, 'total sulfur dioxide': 29.0, 'density': 0.9974, 'pH': 3.26, 'sulphates': 1.56, 'alcohol': 9.1, 'quality': 5}
14 : {'_id': ObjectId('6a1073330a6ca7c75455d4f7'), 'fixed acidity': 8.9, 'volatile acidity': 0.62, 'citric acid': 0.18, 'residual sugar': 3.8, 'chlorides': 0.176, 'free sulfur dioxide': 52.0, 'total sulfur dioxide': 145.0, 'density': 0.9986, 'pH': 3.16, 'sulphates': 0.88, 'alcohol': 9.2, 'quality': 5}
15 : {'_id': ObjectId('6a1073330a6ca7c75455d4f8'), 'fixed acidity': 8.9, 'volatile acidity': 0.62, 'citric acid': 0.19, 'residual sugar': 3.9, 'chlorides': 0.17, 'free sulfur dioxide': 51.0, 'total sulfur dioxide': 148.0, 'density': 0.9986, 'pH': 3.17, 'sulphates': 0.93, 'alcohol': 9.2, 'quality': 5}
16 : {'_id': ObjectId('6a1073330a6ca7c75455d4f9'), 'fixed acidity': 8.5, 'volatile acidity': 0.28, 'citric acid': 0.56, 'residual sugar': 1.8, 'chlorides': 0.092, 'free sulfur dioxide': 35.0, 'total sulfur dioxide': 103.0, 'density': 0.9969, 'pH': 3.3, 'sulphates': 0.75, 'alcohol': 10.5, 'quality': 7}
17 : {'_id': ObjectId('6a1073330a6ca7c75455d4fa'), 'fixed acidity': 8.1, 'volatile acidity': 0.56, 'citric acid': 0.28, 'residual sugar': 1.7, 'chlorides': 0.368, 'free sulfur dioxide': 16.0, 'total sulfur dioxide': 56.0, 'density': 0.9968, 'pH': 3.11, 'sulphates': 1.28, 'alcohol': 9.3, 'quality': 5}
18 : {'_id': ObjectId('6a1073330a6ca7c75455d4fb'), 'fixed acidity': 7.4, 'volatile acidity': 0.59, 'citric acid': 0.08, 'residual sugar': 4.4, 'chlorides': 0.086, 'free sulfur dioxide': 6.0, 'total sulfur dioxide': 29.0, 'density': 0.9974, 'pH': 3.38, 'sulphates': 0.5, 'alcohol': 9.0, 'quality': 4}
19 : {'_id': ObjectId('6a1073330a6ca7c75455d4fc'), 'fixed acidity': 7.9, 'volatile acidity': 0.32, 'citric acid': 0.51, 'residual sugar': 1.8, 'chlorides': 0.341, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 56.0, 'density': 0.9969, 'pH': 3.04, 'sulphates': 1.08, 'alcohol': 9.2, 'quality': 6}
20 : {'_id': ObjectId('6a1073330a6ca7c75455d4fd'), 'fixed acidity': 8.9, 'volatile acidity': 0.22, 'citric acid': 0.48, 'residual sugar': 1.8, 'chlorides': 0.077, 'free sulfur dioxide': 29.0, 'total sulfur dioxide': 60.0, 'density': 0.9968, 'pH': 3.39, 'sulphates': 0.53, 'alcohol': 9.4, 'quality': 6}
21 : {'_id': ObjectId('6a1073330a6ca7c75455d4fe'), 'fixed acidity': 7.6, 'volatile acidity': 0.39, 'citric acid': 0.31, 'residual sugar': 2.3, 'chlorides': 0.0819999999999999, 'free sulfur dioxide': 23.0, 'total sulfur dioxide': 71.0, 'density': 0.9982, 'pH': 3.52, 'sulphates': 0.65, 'alcohol': 9.7, 'quality': 5}
22 : {'_id': ObjectId('6a1073330a6ca7c75455d4ff'), 'fixed acidity': 7.9, 'volatile acidity': 0.43, 'citric acid': 0.21, 'residual sugar': 1.6, 'chlorides': 0.106, 'free sulfur dioxide': 10.0, 'total sulfur dioxide': 37.0, 'density': 0.9966, 'pH': 3.17, 'sulphates': 0.91, 'alcohol': 9.5, 'quality': 5}
23 : {'_id': ObjectId('6a1073330a6ca7c75455d500'), 'fixed acidity': 8.5, 'volatile acidity': 0.49, 'citric acid': 0.11, 'residual sugar': 2.3, 'chlorides': 0.084, 'free sulfur dioxide': 9.0, 'total sulfur dioxide': 67.0, 'density': 0.9968, 'pH': 3.17, 'sulphates': 0.53, 'alcohol': 9.4, 'quality': 5}
24 : {'_id': ObjectId('6a1073330a6ca7c75455d501'), 'fixed acidity': 6.9, 'volatile acidity': 0.4, 'citric acid': 0.14, 'residual sugar': 2.4, 'chlorides': 0.085, 'free sulfur dioxide': 21.0, 'total sulfur dioxide': 40.0, 'density': 0.9968, 'pH': 3.43, 'sulphates': 0.63, 'alcohol': 9.7, 'quality': 6}
25 : {'_id': ObjectId('6a1073330a6ca7c75455d502'), 'fixed acidity': 6.3, 'volatile acidity': 0.39, 'citric acid': 0.16, 'residual sugar': 1.4, 'chlorides': 0.08, 'free sulfur dioxide': 11.0, 'total sulfur dioxide': 23.0, 'density': 0.9955, 'pH': 3.34, 'sulphates': 0.56, 'alcohol': 9.3, 'quality': 5}
26 : {'_id': ObjectId('6a1073330a6ca7c75455d503'), 'fixed acidity': 7.6, 'volatile acidity': 0.41, 'citric acid': 0.24, 'residual sugar': 1.8, 'chlorides': 0.08, 'free sulfur dioxide': 4.0, 'total sulfur dioxide': 11.0, 'density': 0.9962, 'pH': 3.28, 'sulphates': 0.59, 'alcohol': 9.5, 'quality': 5}
27 : {'_id': ObjectId('6a1073330a6ca7c75455d504'), 'fixed acidity': 7.9, 'volatile acidity': 0.43, 'citric acid': 0.21, 'residual sugar': 1.6, 'chlorides': 0.106, 'free sulfur dioxide': 10.0, 'total sulfur dioxide': 37.0, 'density': 0.9966, 'pH': 3.17, 'sulphates': 0.91, 'alcohol': 9.5, 'quality': 5}
28 : {'_id': ObjectId('6a1073330a6ca7c75455d505'), 'fixed acidity': 7.1, 'volatile acidity': 0.71, 'citric acid': 0.0, 'residual sugar': 1.9, 'chlorides': 0.08, 'free sulfur dioxide': 14.0, 'total sulfur dioxide': 35.0, 'density': 0.9972, 'pH': 3.47, 'sulphates': 0.55, 'alcohol': 9.4, 'quality': 5}
29 : {'_id': ObjectId('6a1073330a6ca7c75455d506'), 'fixed acidity': 7.8, 'volatile acidity': 0.645, 'citric acid': 0.0, 'residual sugar': 2.0, 'chlorides': 0.0819999999999999, 'free sulfur dioxide': 8.0, 'total sulfur dioxide': 16.0, 'density': 0.9964, 'pH': 3.38, 'sulphates': 0.59, 'alcohol': 9.8, 'quality': 6}
30 : {'_id': ObjectId('6a1073330a6ca7c75455d507'), 'fixed acidity': 6.7, 'volatile acidity': 0.675, 'citric acid': 0.07, 'residual sugar': 2.4, 'chlorides': 0.089, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 82.0, 'density': 0.9958, 'pH': 3.35, 'sulphates': 0.54, 'alcohol': 10.1, 'quality': 5}
31 : {'_id': ObjectId('6a1073330a6ca7c75455d508'), 'fixed acidity': 6.9, 'volatile acidity': 0.685, 'citric acid': 0.0, 'residual sugar': 2.5, 'chlorides': 0.105, 'free sulfur dioxide': 22.0, 'total sulfur dioxide': 37.0, 'density': 0.9966, 'pH': 3.46, 'sulphates': 0.57, 'alcohol': 10.6, 'quality': 6}
32 : {'_id': ObjectId('6a1073330a6ca7c75455d509'), 'fixed acidity': 8.3, 'volatile acidity': 0.655, 'citric acid': 0.12, 'residual sugar': 2.3, 'chlorides': 0.083, 'free sulfur dioxide': 15.0, 'total sulfur dioxide': 113.0, 'density': 0.9966, 'pH': 3.17, 'sulphates': 0.66, 'alcohol': 9.8, 'quality': 5}
33 : {'_id': ObjectId('6a1073330a6ca7c75455d50a'), 'fixed acidity': 6.9, 'volatile acidity': 0.605, 'citric acid': 0.12, 'residual sugar': 10.7, 'chlorides': 0.073, 'free sulfur dioxide': 40.0, 'total sulfur dioxide': 83.0, 'density': 0.9993, 'pH': 3.45, 'sulphates': 0.52, 'alcohol': 9.4, 'quality': 6}
34 : {'_id': ObjectId('6a1073330a6ca7c75455d50b'), 'fixed acidity': 5.2, 'volatile acidity': 0.32, 'citric acid': 0.25, 'residual sugar': 1.8, 'chlorides': 0.103, 'free sulfur dioxide': 13.0, 'total sulfur dioxide': 50.0, 'density': 0.9957, 'pH': 3.38, 'sulphates': 0.55, 'alcohol': 9.2, 'quality': 5}
35 : {'_id': ObjectId('6a1073330a6ca7c75455d50c'), 'fixed acidity': 7.8, 'volatile acidity': 0.645, 'citric acid': 0.0, 'residual sugar': 5.5, 'chlorides': 0.086, 'free sulfur dioxide': 5.0, 'total sulfur dioxide': 18.0, 'density': 0.9986, 'pH': 3.4, 'sulphates': 0.55, 'alcohol': 9.6, 'quality': 6}
36 : {'_id': ObjectId('6a1073330a6ca7c75455d50d'), 'fixed acidity': 7.8, 'volatile acidity': 0.6, 'citric acid': 0.14, 'residual sugar': 2.4, 'chlorides': 0.086, 'free sulfur dioxide': 3.0, 'total sulfur dioxide': 15.0, 'density': 0.9975, 'pH': 3.42, 'sulphates': 0.6, 'alcohol': 10.8, 'quality': 6}
37 : {'_id': ObjectId('6a1073330a6ca7c75455d50e'), 'fixed acidity': 8.1, 'volatile acidity': 0.38, 'citric acid': 0.28, 'residual sugar': 2.1, 'chlorides': 0.066, 'free sulfur dioxide': 13.0, 'total sulfur dioxide': 30.0, 'density': 0.9968, 'pH': 3.23, 'sulphates': 0.73, 'alcohol': 9.7, 'quality': 7}
38 : {'_id': ObjectId('6a1073330a6ca7c75455d50f'), 'fixed acidity': 5.7, 'volatile acidity': 1.13, 'citric acid': 0.09, 'residual sugar': 1.5, 'chlorides': 0.172, 'free sulfur dioxide': 7.0, 'total sulfur dioxide': 19.0, 'density': 0.994, 'pH': 3.5, 'sulphates': 0.48, 'alcohol': 9.8, 'quality': 4}
39 : {'_id': ObjectId('6a1073330a6ca7c75455d510'), 'fixed acidity': 7.3, 'volatile acidity': 0.45, 'citric acid': 0.36, 'residual sugar': 5.9, 'chlorides': 0.074, 'free sulfur dioxide': 12.0, 'total sulfur dioxide': 87.0, 'density': 0.9978, 'pH': 3.33, 'sulphates': 0.83, 'alcohol': 10.5, 'quality': 5}
40 : {'_id': ObjectId('6a1073330a6ca7c75455d511'), 'fixed acidity': 7.3, 'volatile acidity': 0.45, 'citric acid': 0.36, 'residual sugar': 5.9, 'chlorides': 0.074, 'free sulfur dioxide': 12.0, 'total sulfur dioxide': 87.0, 'density': 0.9978, 'pH': 3.33, 'sulphates': 0.83, 'alcohol': 10.5, 'quality': 5}
41 : {'_id': ObjectId('6a1073330a6ca7c75455d512'), 'fixed acidity': 8.8, 'volatile acidity': 0.61, 'citric acid': 0.3, 'residual sugar': 2.8, 'chlorides': 0.088, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 46.0, 'density': 0.9976, 'pH': 3.26, 'sulphates': 0.51, 'alcohol': 9.3, 'quality': 4}
42 : {'_id': ObjectId('6a1073330a6ca7c75455d513'), 'fixed acidity': 7.5, 'volatile acidity': 0.49, 'citric acid': 0.2, 'residual sugar': 2.6, 'chlorides': 0.332, 'free sulfur dioxide': 8.0, 'total sulfur dioxide': 14.0, 'density': 0.9968, 'pH': 3.21, 'sulphates': 0.9, 'alcohol': 10.5, 'quality': 6}
43 : {'_id': ObjectId('6a1073330a6ca7c75455d514'), 'fixed acidity': 8.1, 'volatile acidity': 0.66, 'citric acid': 0.22, 'residual sugar': 2.2, 'chlorides': 0.069, 'free sulfur dioxide': 9.0, 'total sulfur dioxide': 23.0, 'density': 0.9968, 'pH': 3.3, 'sulphates': 1.2, 'alcohol': 10.3, 'quality': 5}
44 : {'_id': ObjectId('6a1073330a6ca7c75455d515'), 'fixed acidity': 6.8, 'volatile acidity': 0.67, 'citric acid': 0.02, 'residual sugar': 1.8, 'chlorides': 0.05, 'free sulfur dioxide': 5.0, 'total sulfur dioxide': 11.0, 'density': 0.9962, 'pH': 3.48, 'sulphates': 0.52, 'alcohol': 9.5, 'quality': 5}
45 : {'_id': ObjectId('6a1073330a6ca7c75455d516'), 'fixed acidity': 4.6, 'volatile acidity': 0.52, 'citric acid': 0.15, 'residual sugar': 2.1, 'chlorides': 0.054, 'free sulfur dioxide': 8.0, 'total sulfur dioxide': 65.0, 'density': 0.9934, 'pH': 3.9, 'sulphates': 0.56, 'alcohol': 13.1, 'quality': 4}
46 : {'_id': ObjectId('6a1073330a6ca7c75455d517'), 'fixed acidity': 7.7, 'volatile acidity': 0.935, 'citric acid': 0.43, 'residual sugar': 2.2, 'chlorides': 0.114, 'free sulfur dioxide': 22.0, 'total sulfur dioxide': 114.0, 'density': 0.997, 'pH': 3.25, 'sulphates': 0.73, 'alcohol': 9.2, 'quality': 5}
47 : {'_id': ObjectId('6a1073330a6ca7c75455d518'), 'fixed acidity': 8.7, 'volatile acidity': 0.29, 'citric acid': 0.52, 'residual sugar': 1.6, 'chlorides': 0.113, 'free sulfur dioxide': 12.0, 'total sulfur dioxide': 37.0, 'density': 0.9969, 'pH': 3.25, 'sulphates': 0.58, 'alcohol': 9.5, 'quality': 5}
48 : {'_id': ObjectId('6a1073330a6ca7c75455d519'), 'fixed acidity': 6.4, 'volatile acidity': 0.4, 'citric acid': 0.23, 'residual sugar': 1.6, 'chlorides': 0.066, 'free sulfur dioxide': 5.0, 'total sulfur dioxide': 12.0, 'density': 0.9958, 'pH': 3.34, 'sulphates': 0.56, 'alcohol': 9.2, 'quality': 5}
49 : {'_id': ObjectId('6a1073330a6ca7c75455d51a'), 'fixed acidity': 5.6, 'volatile acidity': 0.31, 'citric acid': 0.37, 'residual sugar': 1.4, 'chlorides': 0.074, 'free sulfur dioxide': 12.0, 'total sulfur dioxide': 96.0, 'density': 0.9954, 'pH': 3.32, 'sulphates': 0.58, 'alcohol': 9.2, 'quality': 5}
50 : {'_id': ObjectId('6a1073330a6ca7c75455d51b'), 'fixed acidity': 8.8, 'volatile acidity': 0.66, 'citric acid': 0.26, 'residual sugar': 1.7, 'chlorides': 0.074, 'free sulfur dioxide': 4.0, 'total sulfur dioxide': 23.0, 'density': 0.9971, 'pH': 3.15, 'sulphates': 0.74, 'alcohol': 9.2, 'quality': 5}
51 : {'_id': ObjectId('6a1073330a6ca7c75455d51c'), 'fixed acidity': 6.6, 'volatile acidity': 0.52, 'citric acid': 0.04, 'residual sugar': 2.2, 'chlorides': 0.069, 'free sulfur dioxide': 8.0, 'total sulfur dioxide': 15.0, 'density': 0.9956, 'pH': 3.4, 'sulphates': 0.63, 'alcohol': 9.4, 'quality': 6}
52 : {'_id': ObjectId('6a1073330a6ca7c75455d51d'), 'fixed acidity': 6.6, 'volatile acidity': 0.5, 'citric acid': 0.04, 'residual sugar': 2.1, 'chlorides': 0.068, 'free sulfur dioxide': 6.0, 'total sulfur dioxide': 14.0, 'density': 0.9955, 'pH': 3.39, 'sulphates': 0.64, 'alcohol': 9.4, 'quality': 6}
53 : {'_id': ObjectId('6a1073330a6ca7c75455d51e'), 'fixed acidity': 8.6, 'volatile acidity': 0.38, 'citric acid': 0.36, 'residual sugar': 3.0, 'chlorides': 0.081, 'free sulfur dioxide': 30.0, 'total sulfur dioxide': 119.0, 'density': 0.997, 'pH': 3.2, 'sulphates': 0.56, 'alcohol': 9.4, 'quality': 5}
54 : {'_id': ObjectId('6a1073330a6ca7c75455d51f'), 'fixed acidity': 7.6, 'volatile acidity': 0.51, 'citric acid': 0.15, 'residual sugar': 2.8, 'chlorides': 0.11, 'free sulfur dioxide': 33.0, 'total sulfur dioxide': 73.0, 'density': 0.9955, 'pH': 3.17, 'sulphates': 0.63, 'alcohol': 10.2, 'quality': 6}
55 : {'_id': ObjectId('6a1073330a6ca7c75455d520'), 'fixed acidity': 7.7, 'volatile acidity': 0.62, 'citric acid': 0.04, 'residual sugar': 3.8, 'chlorides': 0.084, 'free sulfur dioxide': 25.0, 'total sulfur dioxide': 45.0, 'density': 0.9978, 'pH': 3.34, 'sulphates': 0.53, 'alcohol': 9.5, 'quality': 5}
56 : {'_id': ObjectId('6a1073330a6ca7c75455d521'), 'fixed acidity': 10.2, 'volatile acidity': 0.42, 'citric acid': 0.57, 'residual sugar': 3.4, 'chlorides': 0.07, 'free sulfur dioxide': 4.0, 'total sulfur dioxide': 10.0, 'density': 0.9971, 'pH': 3.04, 'sulphates': 0.63, 'alcohol': 9.6, 'quality': 5}
57 : {'_id': ObjectId('6a1073330a6ca7c75455d522'), 'fixed acidity': 7.5, 'volatile acidity': 0.63, 'citric acid': 0.12, 'residual sugar': 5.1, 'chlorides': 0.111, 'free sulfur dioxide': 50.0, 'total sulfur dioxide': 110.0, 'density': 0.9983, 'pH': 3.26, 'sulphates': 0.77, 'alcohol': 9.4, 'quality': 5}
58 : {'_id': ObjectId('6a1073330a6ca7c75455d523'), 'fixed acidity': 7.8, 'volatile acidity': 0.59, 'citric acid': 0.18, 'residual sugar': 2.3, 'chlorides': 0.076, 'free sulfur dioxide': 17.0, 'total sulfur dioxide': 54.0, 'density': 0.9975, 'pH': 3.43, 'sulphates': 0.59, 'alcohol': 10.0, 'quality': 5}
59 : {'_id': ObjectId('6a1073330a6ca7c75455d524'), 'fixed acidity': 7.3, 'volatile acidity': 0.39, 'citric acid': 0.31, 'residual sugar': 2.4, 'chlorides': 0.074, 'free sulfur dioxide': 9.0, 'total sulfur dioxide': 46.0, 'density': 0.9962, 'pH': 3.41, 'sulphates': 0.54, 'alcohol': 9.4, 'quality': 6}
60 : {'_id': ObjectId('6a1073330a6ca7c75455d525'), 'fixed acidity': 8.8, 'volatile acidity': 0.4, 'citric acid': 0.4, 'residual sugar': 2.2, 'chlorides': 0.079, 'free sulfur dioxide': 19.0, 'total sulfur dioxide': 52.0, 'density': 0.998, 'pH': 3.44, 'sulphates': 0.64, 'alcohol': 9.2, 'quality': 5}
61 : {'_id': ObjectId('6a1073330a6ca7c75455d526'), 'fixed acidity': 7.7, 'volatile acidity': 0.69, 'citric acid': 0.49, 'residual sugar': 1.8, 'chlorides': 0.115, 'free sulfur dioxide': 20.0, 'total sulfur dioxide': 112.0, 'density': 0.9968, 'pH': 3.21, 'sulphates': 0.71, 'alcohol': 9.3, 'quality': 5}
62 : {'_id': ObjectId('6a1073330a6ca7c75455d527'), 'fixed acidity': 7.5, 'volatile acidity': 0.52, 'citric acid': 0.16, 'residual sugar': 1.9, 'chlorides': 0.085, 'free sulfur dioxide': 12.0, 'total sulfur dioxide': 35.0, 'density': 0.9968, 'pH': 3.38, 'sulphates': 0.62, 'alcohol': 9.5, 'quality': 7}
63 : {'_id': ObjectId('6a1073330a6ca7c75455d528'), 'fixed acidity': 7.0, 'volatile acidity': 0.735, 'citric acid': 0.05, 'residual sugar': 2.0, 'chlorides': 0.081, 'free sulfur dioxide': 13.0, 'total sulfur dioxide': 54.0, 'density': 0.9966, 'pH': 3.39, 'sulphates': 0.57, 'alcohol': 9.8, 'quality': 5}
64 : {'_id': ObjectId('6a1073330a6ca7c75455d529'), 'fixed acidity': 7.2, 'volatile acidity': 0.725, 'citric acid': 0.05, 'residual sugar': 4.65, 'chlorides': 0.086, 'free sulfur dioxide': 4.0, 'total sulfur dioxide': 11.0, 'density': 0.9962, 'pH': 3.41, 'sulphates': 0.39, 'alcohol': 10.9, 'quality': 5}
65 : {'_id': ObjectId('6a1073330a6ca7c75455d52a'), 'fixed acidity': 7.2, 'volatile acidity': 0.725, 'citric acid': 0.05, 'residual sugar': 4.65, 'chlorides': 0.086, 'free sulfur dioxide': 4.0, 'total sulfur dioxide': 11.0, 'density': 0.9962, 'pH': 3.41, 'sulphates': 0.39, 'alcohol': 10.9, 'quality': 5}

In [15]:
df = pd.DataFrame(list(collection.find()))

In [16]:
df.head()

,_id,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,6a1073330a6ca7c75455d4e9,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,6a1073330a6ca7c75455d4ea,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,6a1073330a6ca7c75455d4eb,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,6a1073330a6ca7c75455d4ec,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,6a1073330a6ca7c75455d4ed,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [17]:
if "_id" in df.columns.to_list():
    df.drop(columns=["_id"], inplace=True)

In [18]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5